#pragma once

#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE

#define SERIAL_USART_FULL_DUPLEX

#define BOOTMAGIC_ROW_RIGHT 6
#define BOOTMAGIC_COLUMN_RIGHT 0

// VIA Configuration
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

