#pragma once

#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE

#define SERIAL_USART_FULL_DUPLEX

#define BOOTMAGIC_ROW_RIGHT 6
#define BOOTMAGIC_COLUMN_RIGHT 0

// VIA Configuration
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

#define MOUSEKEY_DELAY 4
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INTERVAL 3
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 140
